Displaying errors

diff --git a/bin/tomcatadmin b/bin/tomcatadmin
--- a/bin/tomcatadmin
+++ b/bin/tomcatadmin
@@ -27,8 +27,69 @@ EOF
 }
 
 die() {
-    echo $1
+    echo $1>&2
     exit 2
+}
+
+doCurl() {
+    $(curl -s -u $user $url$*)
+    status=$?
+    case $status in 
+	0)
+	    ;;
+
+	2)
+	    echo "Failed to initialize."
+	    ;;
+	3)
+	    echo "URL malformed. The syntax was not correct."
+	    ;;
+	4)
+	    echo "A feature or option that was needed to perform the desired request was not enabled or was explicitly disabled at build-time. To make curl able to do this, you probably need another build of libcurl!"
+	    ;;
+	5)
+	    echo "Couldn't resolve proxy. The given proxy host could not be resolved."
+	    ;;
+	6)
+	    echo "Couldn't resolve host. The given remote host was not resolved."
+	    ;;
+	7)
+	    echo "Failed to connect to host."
+	    ;;
+	18)
+	    echo "Partial file. Only a part of the file was transferred."
+	    ;;
+	22)
+	    echo "HTTP page not retrieved. The requested url was not found or returned another error with the HTTP error code being 400 or above. This return  code  only  appears  if  -f, --fail is used."
+	    ;;
+	23)
+	    echo "Write error. Curl couldn't write data to a local filesystem or similar."
+	    ;;
+	26)
+	    echo "Read error. Various reading problems."
+	    ;;
+	27)
+	    echo "Out of memory. A memory allocation request failed."
+	    ;;
+	28)
+	    echo "Operation timeout. The specified time-out period was reached according to the conditions."
+	    ;;
+	33)
+	    echo "HTTP range error. The range "command" didn't work."
+	    ;;
+	34)
+	    echo "HTTP post error. Internal post-request generation error."
+	    ;;
+	35)
+	    echo "SSL connect error. The SSL handshaking failed."
+	    ;;
+	*)
+	    echo "Error $status check curl manpage" >&2
+	    ;;
+    esac
+    if [ $status -ne 0 ]; then
+	exit $status
+    fi
 }
 
 
@@ -38,7 +99,7 @@ port=8080
 manager=/manager/text/
 
 
-while getopts "h:u:" opt; do
+while getopts "h:u:p:" opt; do
     case $opt in
 	h)
 	    host=$OPTARG
@@ -46,11 +107,12 @@ while getopts "h:u:" opt; do
 	u)
 	    user=$OPTARG
 	    ;;
+	p)
+	    port=$OPTARG
+	    ;;
 	*)
-	    usage
-	    
-    esac
-    
+	    usage	    
+    esac    
 done
 
 shift $(($OPTIND-1))
@@ -73,21 +135,20 @@ if [ $cmd != "list" -a $cmd != "serverinfo" -a $cmd != "resources" ]; then
     path=$1
 fi
 
-curl="curl -s -u $user $url"
 
 case $cmd in
     list|serverinfo)
-	${curl}$cmd
+	doCurl $cmd
 	;;
     resources)
 	if [ $# -eq 1 ]; then
-	    ${curl}$cmd?$*
+	    doCurl $cmd?$*
 	else
-	    ${curl}$cmd
+	    doCurl $cmd
         fi
 	;;
     status)
-        status=$(${curl}list | grep "$path:" | awk -F: '{print $2}')
+        status=$(doCurl list | grep "$path:" | awk -F: '{print $2}')
 	echo $status
 	if [ -z $status ]; then
 	    exit 2
@@ -99,7 +160,7 @@ case $cmd in
 
 	;;
     start|stop|reload|undeploy)
-	result=$(${curl}$cmd?path=$path)
+	result=$(doCurl $cmd?path=$path)
 	echo $result
 	if [[ $result == OK* ]] ; then
 	    exit 0;
@@ -119,7 +180,7 @@ case $cmd in
 	if [ $cmd = "redeploy" ]; then
 	    redeploy="&update=true"
         fi
-	${curl}deploy?path=$path$redeploy -T $file 
+	doCurl deploy?path=$path$redeploy -T $file 
 	;;
     *)
 	die "Unsupported command: $cmd"
